kc_flight_states = "COLD&DARK|PREL PRE-FLIGHT|PRE-FLIGHT"

activeBckVars = kcPreferenceSet:new("BackgroundVars")

local group1 = kcPreferenceGroup:new("general","General Variables")
group1:add(kcPreference:new("flight_state",1,kcPreference.typeList,"Flight States|" .. kc_flight_states))

local group2 = kcPreferenceGroup:new("ui","UI Settings")
group2:add(kcPreference:new("sop_wnd_ypos",70,kcPreference.typeInt,"SOP Window Y Pos|"))
group2:add(kcPreference:new("sop_wnd_xoffset",50,kcPreference.typeInt,"SOP Window x offset from right|"))
group2:add(kcPreference:new("flow_wnd_xpos",30,kcPreference.typeInt,"Flow Window x position|"))
group2:add(kcPreference:new("flow_wnd_ypos",70,kcPreference.typeInt,"Flow Window y position|"))
group2:add(kcPreference:new("flow_line_length",55,kcPreference.typeInt,"Flow text line length|"))


local group3 = kcPreferenceGroup:new("procvars","Procedure Variables")
group3:add(kcPreference:new("takeoff_config_warn",false,kcPreference.typeToggle,"takeoff_config_warn|TRUE|FALSE"))
group3:add(kcPreference:new("cargo_fire_test",false,kcPreference.typeToggle,"cargo_fire_test|TRUE|FALSE"))
group3:add(kcPreference:new("master_fire_warn",false,kcPreference.typeToggle,"master_fire_warn|TRUE|FALSE"))
group3:add(kcPreference:new("eng_ext_test_1",false,kcPreference.typeToggle,"eng_ext_test_1|TRUE|FALSE"))
group3:add(kcPreference:new("eng_ext_test_2",false,kcPreference.typeToggle,"eng_ext_test_2|TRUE|FALSE"))
group3:add(kcPreference:new("apu_fire_test",false,kcPreference.typeToggle,"apu_fire_test|TRUE|FALSE"))
group3:add(kcPreference:new("attendence_button",false,kcPreference.typeToggle,"attendence_button|TRUE|FALSE"))
group3:add(kcPreference:new("irs_mode_initial_off",false,kcPreference.typeToggle,"irs_mode_initial_off|TRUE|FALSE"))
group3:add(kcPreference:new("irs_mode_nav_again",false,kcPreference.typeToggle,"irs_mode_nav_again|TRUE|FALSE"))
group3:add(kcPreference:new("irs_left_dc",false,kcPreference.typeToggle,"irs_left_dc|TRUE|FALSE"))
group3:add(kcPreference:new("irs_right_dc",false,kcPreference.typeToggle,"irs_right_dc|TRUE|FALSE"))
group3:add(kcPreference:new("irs_left_align",false,kcPreference.typeToggle,"irs_left_align|TRUE|FALSE"))
group3:add(kcPreference:new("irs_right_align",false,kcPreference.typeToggle,"irs_right_align|TRUE|FALSE"))
group3:add(kcPreference:new("mach_ovspd_test",false,kcPreference.typeToggle,"mach_ovspd_test|TRUE|FALSE"))
group3:add(kcPreference:new("stall_warning_test",false,kcPreference.typeToggle,"stall_warning_test|TRUE|FALSE"))
group3:add(kcPreference:new("ident_page",false,kcPreference.typeToggle,"ident_page|TRUE|FALSE"))
group3:add(kcPreference:new("pos_init_page",false,kcPreference.typeToggle,"pos_init_page|TRUE|FALSE"))
group3:add(kcPreference:new("ref_airport_set",false,kcPreference.typeToggle,"ref_airport_set|TRUE|FALSE"))
group3:add(kcPreference:new("rte_page",false,kcPreference.typeToggle,"rte_page|TRUE|FALSE"))
group3:add(kcPreference:new("origin_set",false,kcPreference.typeToggle,"origin_set|TRUE|FALSE"))
group3:add(kcPreference:new("dest_set",false,kcPreference.typeToggle,"dest_set|TRUE|FALSE"))
group3:add(kcPreference:new("flt_no_entered",false,kcPreference.typeToggle,"flt_no_entered|TRUE|FALSE"))
group3:add(kcPreference:new("route_entered",false,kcPreference.typeToggle,"route_entered|TRUE|FALSE"))
group3:add(kcPreference:new("route_activated",false,kcPreference.typeToggle,"route_activated|TRUE|FALSE"))
group3:add(kcPreference:new("departures_open",false,kcPreference.typeToggle,"departures_open|TRUE|FALSE"))
group3:add(kcPreference:new("legs_page_open",false,kcPreference.typeToggle,"legs_page_open|TRUE|FALSE"))
group3:add(kcPreference:new("perf_init_page",false,kcPreference.typeToggle,"perf_init_page|TRUE|FALSE"))
group3:add(kcPreference:new("zfw_entered",false,kcPreference.typeToggle,"zfw_entered|TRUE|FALSE"))
group3:add(kcPreference:new("crz_alt_entered",false,kcPreference.typeToggle,"crz_alt_entered|TRUE|FALSE"))
group3:add(kcPreference:new("gw_entered",false,kcPreference.typeToggle,"gw_entered|TRUE|FALSE"))
group3:add(kcPreference:new("reserves_entered",false,kcPreference.typeToggle,"reserves_entered|TRUE|FALSE"))
group3:add(kcPreference:new("cost_index_entered",false,kcPreference.typeToggle,"cost_index_entered|TRUE|FALSE"))
group3:add(kcPreference:new("n1_limit_page",false,kcPreference.typeToggle,"n1_limit_page|TRUE|FALSE"))
group3:add(kcPreference:new("takeoff_ref_page",false,kcPreference.typeToggle,"takeoff_ref_page|TRUE|FALSE"))
group3:add(kcPreference:new("flaps_entered",false,kcPreference.typeToggle,"flaps_entered|TRUE|FALSE"))
group3:add(kcPreference:new("cg_entered",false,kcPreference.typeToggle,"cg_entered|TRUE|FALSE"))
group3:add(kcPreference:new("vspeeds_entered",false,kcPreference.typeToggle,"vspeeds_entered|TRUE|FALSE"))
group3:add(kcPreference:new("internal_lights_test",false,kcPreference.typeToggle,"internal_lights_test|TRUE|FALSE"))
group3:add(kcPreference:new("voice_recorder_test",false,kcPreference.typeToggle,"voice_recorder_test|TRUE|FALSE"))
group3:add(kcPreference:new("hyd_press_test",false,kcPreference.typeToggle,"hyd_press_test|TRUE|FALSE"))
group3:add(kcPreference:new("pb_parkbrk_initial_set",false,kcPreference.typeToggle,"pb_parkbrk_initial_set|TRUE|FALSE"))
group3:add(kcPreference:new("pb_parkbrk_release",false,kcPreference.typeToggle,"pb_parkbrk_release|TRUE|FALSE"))

activeBckVars:addGroup(group1)
activeBckVars:addGroup(group2)
activeBckVars:addGroup(group3)

function getBckVars()
	return activeBckVars
end

return backgroundVars