-- Rotate MD88 airplane 
-- macros

-- @classmod sysMacros
-- @author Kosta Prokopiu
-- @copyright 2024 Kosta Prokopiu

local sysMacros = {
}

-- ====================================== States related macros
function kc_macro_state_cold_and_dark()
	logMsg("kc_macro_state_cold_and_dark")
	kc_macro_lights_cold_dark()
	kc_macro_doors_cold_dark()
	kc_macro_mcp_cold_dark()

	sysGeneral.parkBrakeSwitch:actuate(1)
	set("Rotate/md80/hydraulic/hyd_switch_l",0)
	set("Rotate/md80/hydraulic/hyd_switch_r",0)
	set("sim/cockpit2/controls/rudder_trim",0) 
	set("sim/cockpit2/controls/aileron_trim",0)	
	set("Rotate/md80/air/cabin_press_control_lever",0)
	set("Rotate/md80/systems/emergency_lights_switch",0)
	set("Rotate/md80/air/APU_bleed_air_switch",0)
	set("Rotate/md80/fuel/start_pump",0)
	set("Rotate/md80/fuel/right_aft_pump",0)	
	set("Rotate/md80/air/aircon_shutoff_ovrd",0)
	set("Rotate/md80/air/air_pack_left_switch",0)
	set("Rotate/md80/air/air_pack_right_switch",0)
	sysFuel.allFuelPumpGroup:actuate(0)
	sysAir.bleedEng1Switch:actuate(0)	
	sysAir.bleedEng2Switch:actuate(0)	
	sysAir.apuBleedSwitch:actuate(0)	
	set("Rotate/md80/systems/auto_brake_level",1)
	set("Rotate/md80/electrical/APU_gs_bus_switch",0)
	set("Rotate/md80/electrical/GPU_gs_bus_switch",0)
	set("Rotate/md80/systems/flt_recorder_switch",0)
	set("Rotate/md80/systems/fire_det_loop_selector_apu",1) 
	set("Rotate/md80/systems/fire_det_loop_selector_l",1) 
	set("Rotate/md80/systems/fire_det_loop_selector_r",1) 
	set("Rotate/md80/electrical/power_indicator_switch",0)
	set("Rotate/md80/electrical/emergency_power_switch",0)
	set("Rotate/md80/engines/igniter_switch",1)
	set("Rotate/md80/systems/seatbelts_switch",0)
	set("Rotate/md80/systems/no_smoking_switch",0)
	set("Rotate/md80/ice/probes_antiice_switch",0) 
	set("Rotate/md80/ice/airfoil_antiice",0) 
	set("Rotate/md80/systems/windshield_antifog_switch",0)
	set("Rotate/md80/ice/windshield_antiice_switch",0)
	set("Rotate/md80/systems/eng_sync_switch",1)
	set("Rotate/md80/hydraulic/anti_skid_arm",0)
	set("Rotate/md80/systems/yaw_damper_switch",0)
	set("Rotate/md80/systems/mach_trim_comp_override",0)
	set("Rotate/md80/air/temp_control_cockpit_setting",0.5)
	set("Rotate/md80/air/temp_control_cabin_setting",0.5 )
	set("Rotate/md80/air/aircon_ram_air",0)
	set("Rotate/md80/fuel/fuel_test_button_active",0)
	set("Rotate/md80/hydraulic/hyd_switch_electric",0)
	set("Rotate/md80/hydraulic/hyd_trans",0)
	set("Rotate/md80/ice/engine_antiice_left",0)		
	set("Rotate/md80/ice/engine_antiice_right",0) 
	set("Rotate/md80/systems/brake_temp_selector",0)
	set("Rotate/md80/instruments/wx_switch",0)
	set("Rotate/md80/hydraulic/rudder_control_manual",0)
	set("Rotate/md80/systems/static_air_l",0)
	set("Rotate/md80/systems/static_air_r",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_l",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_r",0)
	set("Rotate/md80/fuel/fuel_xfeed_valve_ratio",0)
	set("Rotate/md80/instruments/transponder_mode_switch",0) 
	set("Rotate/md80/fms/irs2_status",0)
	set("Rotate/md80/fms/irs_status",0)
	set("Rotate/md80/electrical/generator_switch_0",0)
	set("Rotate/md80/electrical/generator_switch_1",0)
	set("Rotate/md80/electrical/galley_switch",0)
	set("Rotate/md80/autopilot/cadc_select",1)
	set("Rotate/md80/autopilot/fd_select",1)
	set("Rotate/md80/autopilot/ahrs_select",1)
	set("Rotate/md80/autopilot/efis_select",1)
	set("Rotate/md80/autopilot/nav_source_select",1)
	set("Rotate/md80/electrical/ac_bus_tie_switch",0)
	set("Rotate/md80/misc/fire_ext_apu_disch_1",0)
	set("Rotate/md80/misc/fire_ext_apu_disch_2",0)
	set("Rotate/md80/misc/fire_cont_switch",0)
	set("Rotate/md80/systems/apu_doors_switch",0)
	set("Rotate/md80/electrical/dc_bus_tie_switch",1)
	set("Rotate/md80/fuel/fuel_heat_l_active",0)
	set("Rotate/md80/fuel/fuel_heat_r_active",0)
	set("Rotate/md80/engines/engine_l_start_switch",0)
	set("Rotate/md80/engines/engine_r_start_switch",0)
	set("Rotate/md80/instruments/transponder_scope_switch",1)
	set("Rotate/md80/instruments/transponder_altitude_selector",1)
	set("Rotate/md80/systems/to_flap_angle",0)
	set("Rotate/md80/systems/cg_percent_mac",0)
	set("Rotate/md80/systems/flap_handle_position_ratio",0)
	sysElectric.apuGenBus1:actuate(0)
	sysElectric.apuGenBus2:actuate(0)
	sysElectric.apuStartSwitch:actuate(0)
	sysElectric.gpuGenBus1:actuate(0)
	sysElectric.gpuGenBus2:actuate(0)
	set("Rotate/md80/electrical/GPU_power_available",0)
	sysGeneral.parkBrakeSwitch:actuate(1)
	set("Rotate/md80/systems/speedbrake_position",0)	 
	sysControls.flapsSwitch:actuate(0)	
	sysHydraulic.elecHydPumpGroup:actuate(0)	
	sysGeneral.GearSwitch:actuate(1)
	sysGeneral.wiperGroup:actuate(1)	
	
	set("Rotate/md80/electrical/battery_on",0)	
	
	set("sim/private/controls/shadow/cockpit_near_adjust",0.09)
	activeBckVars:set("general:timesOFF","==:==")
	activeBckVars:set("general:timesOUT","==:==")
	activeBckVars:set("general:timesIN","==:==")
	activeBckVars:set("general:timesON","==:==")
	

	command_once("Rotate/md80/doors/main_stair_open")


end

function kc_macro_state_turnaround()
	logMsg("kc_macro_state_turnaround")
	
	kc_macro_lights_preflight()
	kc_macro_doors_preflight()
	kc_macro_mcp_cold_dark()

	sysGeneral.parkBrakeSwitch:actuate(1)
	set("Rotate/md80/hydraulic/hyd_switch_l",0)
	set("Rotate/md80/hydraulic/hyd_switch_r",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_l",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_r",0)
	set("sim/cockpit2/controls/rudder_trim",0) 
	set("sim/cockpit2/controls/aileron_trim",0)	
	set("Rotate/md80/air/cabin_press_control_lever",0)
	set("Rotate/md80/systems/emergency_lights_switch",0)
	set("Rotate/md80/air/APU_bleed_air_switch",0)
	set("Rotate/md80/fuel/start_pump",0)
	set("Rotate/md80/fuel/right_aft_pump",0)	
	set("Rotate/md80/systems/static_air_l",0)
	set("Rotate/md80/air/aircon_shutoff_ovrd",0)
	set("Rotate/md80/air/air_pack_left_switch",0)
	set("Rotate/md80/air/air_pack_right_switch",0)
	sysFuel.allFuelPumpGroup:actuate(0)
	sysAir.bleedEng1Switch:actuate(0)	
	sysAir.bleedEng2Switch:actuate(0)	
	sysAir.apuBleedSwitch:actuate(0)	
	set("Rotate/md80/systems/auto_brake_level",1)
	set("Rotate/md80/electrical/APU_gs_bus_switch",0)
	set("Rotate/md80/electrical/GPU_gs_bus_switch",0)
	set("Rotate/md80/systems/flt_recorder_switch",0)
	set("Rotate/md80/systems/fire_det_loop_selector_apu",1) 
	set("Rotate/md80/systems/fire_det_loop_selector_l",1) 
	set("Rotate/md80/systems/fire_det_loop_selector_r",1) 
	set("Rotate/md80/electrical/power_indicator_switch",0)
	set("Rotate/md80/electrical/emergency_power_switch",0)
	set("Rotate/md80/engines/igniter_switch",1)
	set("Rotate/md80/systems/seatbelts_switch",0)
	set("Rotate/md80/systems/no_smoking_switch",0)
	set("Rotate/md80/ice/probes_antiice_switch",0) 
	set("Rotate/md80/ice/airfoil_antiice",0) 
	set("Rotate/md80/systems/windshield_antifog_switch",0)
	set("Rotate/md80/ice/windshield_antiice_switch",0)
	set("Rotate/md80/systems/eng_sync_switch",1)
	set("Rotate/md80/hydraulic/anti_skid_arm",0)
	set("Rotate/md80/systems/yaw_damper_switch",0)
	set("Rotate/md80/systems/mach_trim_comp_override",0)
	set("Rotate/md80/air/temp_control_cockpit_setting",0.5)
	set("Rotate/md80/air/temp_control_cabin_setting",0.5 )
	set("Rotate/md80/air/aircon_ram_air",0)
	set("Rotate/md80/fuel/fuel_test_button_active",0)
	set("Rotate/md80/air/temp_control_cockpit_setting",0)
	set("Rotate/md80/air/temp_control_cabin_setting",0)
	set("Rotate/md80/hydraulic/hyd_switch_electric",0)
	set("Rotate/md80/hydraulic/hyd_trans",0)
	set("Rotate/md80/ice/engine_antiice_left",0)		
	set("Rotate/md80/ice/engine_antiice_right",0) 
	set("Rotate/md80/systems/brake_temp_selector",0)
	set("Rotate/md80/instruments/wx_switch",0)
	set("Rotate/md80/hydraulic/rudder_control_manual",0)
	set("Rotate/md80/systems/static_air_l",0)
	set("Rotate/md80/systems/static_air_r",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_l",0)
	set("Rotate/md80/fuel/fuel_valve_ratio_r",0)
	set("Rotate/md80/fuel/fuel_xfeed_valve_ratio",0)
	set("Rotate/md80/instruments/transponder_mode_switch",0) 
	set("Rotate/md80/fms/irs2_status",0)
	set("Rotate/md80/fms/irs_status",0)
	set("Rotate/md80/electrical/generator_switch_0",0)
	set("Rotate/md80/electrical/generator_switch_1",0)
	set("Rotate/md80/electrical/galley_switch",0)
	set("Rotate/md80/autopilot/cadc_select",1)
	set("Rotate/md80/autopilot/fd_select",1)
	set("Rotate/md80/autopilot/ahrs_select",1)
	set("Rotate/md80/autopilot/efis_select",1)
	set("Rotate/md80/autopilot/nav_source_select",1)
	set("Rotate/md80/electrical/ac_bus_tie_switch",0)
	set("Rotate/md80/misc/fire_ext_apu_disch_1",0)
	set("Rotate/md80/misc/fire_ext_apu_disch_2",0)
	set("Rotate/md80/misc/fire_cont_switch",0)
	set("Rotate/md80/systems/apu_doors_switch",0)
	set("Rotate/md80/electrical/dc_bus_tie_switch",1)
	set("Rotate/md80/fuel/fuel_heat_l_active",0)
	set("Rotate/md80/fuel/fuel_heat_r_active",0)
	set("Rotate/md80/engines/engine_l_start_switch",0)
	set("Rotate/md80/engines/engine_r_start_switch",0)
	set("Rotate/md80/misc/fire_cont_switch",0)
	set("Rotate/md80/instruments/transponder_scope_switch",1)
	set("Rotate/md80/instruments/transponder_altitude_selector",1)
	set("Rotate/md80/systems/to_flap_angle",0)
	set("Rotate/md80/systems/cg_percent_mac",0)
	set("Rotate/md80/systems/flap_handle_position_ratio",0)
	sysElectric.apuGenBus1:actuate(0)
	sysElectric.apuGenBus2:actuate(0)
	sysElectric.apuStartSwitch:actuate(0)
	sysElectric.gpuGenBus1:actuate(0)
	sysElectric.gpuGenBus2:actuate(0)
	set("Rotate/md80/electrical/GPU_power_available",0)
	sysGeneral.parkBrakeSwitch:actuate(1)
	set("Rotate/md80/systems/speedbrake_position",0)	 
	sysControls.flapsSwitch:actuate(0)	
	sysHydraulic.elecHydPumpGroup:actuate(0)	
	sysGeneral.GearSwitch:actuate(1)
	sysGeneral.wiperGroup:actuate(1)	
	
	
	set("Rotate/md80/electrical/battery_on",0)	
	
	set("sim/private/controls/shadow/cockpit_near_adjust",0.09)
	activeBckVars:set("general:timesOFF","==:==")
	activeBckVars:set("general:timesOUT","==:==")
	activeBckVars:set("general:timesIN","==:==")
	activeBckVars:set("general:timesON","==:==")
	

	command_once("Rotate/md80/doors/main_stair_open")
	
	
end

-- ====================================== Lights related functions
function kc_macro_lights_preflight()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",0)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/wing_light_switch",0)
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0.5)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",1)
		set("Rotate/md80/lights/wing_light_switch",1)	
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,1)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",1)
	end
	
end
	
function kc_macro_lights_before_start()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0.5)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",1)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0.5)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.5)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.5)
	end
end

function kc_macro_lights_before_taxi()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",1)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",1)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end

end

function kc_macro_lights_for_takeoff()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",2)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",2)
	set("Rotate/md80/lights/nose_light_switch",2)
	set("Rotate/md80/lights/flood_light_switch_l",1)
	set("Rotate/md80/lights/flood_light_switch_r",1)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",2)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end


end

function kc_macro_lights_climb_10k()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",2)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end

end

function kc_macro_lights_descend_10k()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",2)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",2)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",2)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end

end

function kc_macro_lights_approach()

	set("Rotate/md80/lights/wing_ldg_light_switch_l",2)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",2)
	set("Rotate/md80/lights/nose_light_switch",1)
	set("Rotate/md80/lights/flood_light_switch_l",1)
	set("Rotate/md80/lights/flood_light_switch_r",1)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",2)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end
end

function kc_macro_lights_cleanup()
	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",2)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",1)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0.1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0.1)
	end
end

function kc_macro_lights_arrive_parking()
	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",0)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",1)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,1)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",1)
	end
end

function kc_macro_lights_after_shutdown()
	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",0)
	set("Rotate/md80/lights/pos_strobe_light_switch",1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,1)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,1)
	set("sim/cockpit/electrical/instrument_brightness",1)
	set("sim/cockpit/radios/transponder_brightness",1)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",1)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0.5)
	set("Rotate/md80/lights/dfgc_panel_dimm",1)
	set("Rotate/md80/lights/dfgc_digital_dimm",1)
	set("Rotate/md80/lights/wing_light_switch",1)	
	
	if kc_is_daylight() then	
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0.5)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
	else
		set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",1)
		set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,1)
		set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",1)
		set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",1)
	end
end

function kc_macro_lights_cold_dark()
	set("Rotate/md80/lights/wing_ldg_light_switch_l",0)
	set("Rotate/md80/lights/wing_ldg_light_switch_r",0)
	set("Rotate/md80/lights/nose_light_switch",0)
	set("Rotate/md80/lights/flood_light_switch_l",0)
	set("Rotate/md80/lights/flood_light_switch_r",0)
	set("Rotate/md80/lights/anticollision_light_switch",0)
	set("Rotate/md80/lights/pos_strobe_light_switch",0)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",2,0)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",1,0)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",0,0)
	set("sim/cockpit/electrical/instrument_brightness",0)
	set("sim/cockpit/radios/transponder_brightness",0)
	set("Rotate/md80/lights/cockpit_panel_digital_lt_dimm",0)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
	set("Rotate/md80/lights/dfgc_panel_dimm",0)
	set("Rotate/md80/lights/dfgc_digital_dimm",0)
	set("Rotate/md80/lights/wing_light_switch",0)	
	
	set("Rotate/md80/lights/cockpit_panel_instr_lt_dimm",0)
	set_array("sim/cockpit2/switches/instrument_brightness_ratio",11,0)
	set("Rotate/md80/lights/cockpit_ovhd_instr_lt_dimm",0)
	set("Rotate/md80/lights/cockpit_ovhd_flood_lt_dimm",0)
	set("Rotate/md80/lights/cockpit_panel_flood_lt_dimm",0)
end

-- ====================================== Door related functions

function kc_macro_doors_preflight()
	sysGeneral.doorL1:actuate(1)
	sysGeneral.doorL2:actuate(0)
	sysGeneral.doorR1:actuate(0)
	sysGeneral.doorR2:actuate(0)
	sysGeneral.doorFCargo:actuate(1)
	sysGeneral.doorACargo:actuate(1)
	sysGeneral.cockpitDoor:actuate(1)
	sysGeneral.stairs:actuate(1)
end

function kc_macro_doors_before_start()
	sysGeneral.doorL1:actuate(0)
	sysGeneral.doorL2:actuate(0)
	sysGeneral.doorR1:actuate(0)
	sysGeneral.doorR2:actuate(0)
	sysGeneral.doorFCargo:actuate(0)
	sysGeneral.doorACargo:actuate(0)
	sysGeneral.cockpitDoor:actuate(0)
	sysGeneral.stairs:actuate(0)
end

function kc_macro_doors_after_shutdown()
	sysGeneral.doorL1:actuate(1)
	sysGeneral.doorL2:actuate(0)
	sysGeneral.doorR1:actuate(0)
	sysGeneral.doorR2:actuate(0)
	sysGeneral.doorFCargo:actuate(1)
	sysGeneral.doorACargo:actuate(1)
	sysGeneral.cockpitDoor:actuate(1)
end

function kc_macro_doors_cold_dark()
	sysGeneral.doorL1:actuate(1)
	sysGeneral.doorL2:actuate(0)
	sysGeneral.doorR1:actuate(0)
	sysGeneral.doorR2:actuate(0)
	sysGeneral.doorFCargo:actuate(0)
	sysGeneral.doorACargo:actuate(0)
	sysGeneral.cockpitDoor:actuate(1)
	sysGeneral.stairs:actuate(1)
end

function kc_macro_doors_all_open()
	sysGeneral.doorL1:actuate(1)
	sysGeneral.doorL2:actuate(1)
	sysGeneral.doorR1:actuate(1)
	sysGeneral.doorR2:actuate(1)
	sysGeneral.doorFCargo:actuate(1)
	sysGeneral.doorACargo:actuate(1)
	sysGeneral.cockpitDoor:actuate(1)
	sysGeneral.stairs:actuate(1)
end

function kc_macro_doors_all_closed()
	sysGeneral.doorL1:actuate(0)
	sysGeneral.doorL2:actuate(0)
	sysGeneral.doorR1:actuate(0)
	sysGeneral.doorR2:actuate(0)
	sysGeneral.doorFCargo:actuate(0)
	sysGeneral.doorACargo:actuate(0)
	sysGeneral.cockpitDoor:actuate(0)
	sysGeneral.stairs:actuate(0)
end

-- ====================================== A/P & Glareshield related functions

function kc_macro_mcp_cold_dark()
	sysMCP.fdirPilotSwitch:actuate(0)
	sysMCP.athrSwitch:actuate(0)
	sysMCP.crs1Selector:setValue(1)
	sysMCP.crs2Selector:setValue(1)
	sysMCP.iasSelector:setValue(activePrefSet:get("aircraft:mcp_def_spd"))
	sysMCP.hdgSelector:setValue(activePrefSet:get("aircraft:mcp_def_hdg"))
	sysMCP.altSelector:setValue(activePrefSet:get("aircraft:mcp_def_alt"))
	sysMCP.vspSelector:setValue(0)
	sysMCP.discAPSwitch:actuate(0)
	sysMCP.yawDamper:actuate(0)
	sysMCP.ap1Switch:actuate(0)
end

function kc_macro_mcp_preflight()
	sysMCP.fdirPilotSwitch:actuate(1)
	sysMCP.athrSwitch:actuate(0)
	sysMCP.iasSelector:setValue(activeBriefings:get("takeoff:v2"))
	sysMCP.hdgSelector:setValue(activeBriefings:get("departure:initHeading"))
	sysMCP.altSelector:setValue(activeBriefings:get("departure:initAlt"))
	sysMCP.vspSelector:setValue(0)
	sysMCP.discAPSwitch:actuate(0)
	sysMCP.yawDamper:actuate(0)
end

function kc_is_preflight_fgcp_checked()
	return
		get("Rotate/md80/autopilot/fd_toggle") == 1
-- A/P OFF
end

function kc_macro_mcp_takeoff()
	sysMCP.fdirPilotSwitch:actuate(1)
	sysMCP.athrSwitch:actuate(1)
	sysMCP.iasSelector:setValue(activeBriefings:get("takeoff:v2"))
	sysMCP.hdgSelector:setValue(activeBriefings:get("departure:initHeading"))
	sysMCP.altSelector:setValue(activeBriefings:get("departure:initAlt"))
	sysMCP.yawDamper:actuate(1)
	sysMCP.ap1Switch:actuate(0)
end

function kc_macro_mcp_after_landing()
	sysMCP.fdirPilotSwitch:actuate(0)
	sysMCP.athrSwitch:actuate(0)
	sysMCP.iasSelector:setValue(100)
	sysMCP.hdgSelector:setValue(001)
	sysMCP.altSelector:setValue(0100)
	sysMCP.yawDamper:actuate(0)
	sysMCP.ap1Switch:actuate(0)
end

return sysMacros